### ISSUE TITLE
New base units not usable in @context in @import-ed file

### ISSUE THREAD

**Issue by khaeru** [hgrecco/pint#1498]
Pint 0.19 introduces a regression versus 0.18.

Run the following, e.g. `python bug.py`:
```py
from pathlib import Path

import pint


# A file that defines a new base unit and uses it in a context
Path("defs0.txt").write_text("""
foo = [FOO]

@context BAR
    [FOO] -> [mass]: value / foo * 10.0 kg
@end
""")

# A file that defines a new base unit, then imports another file…
Path("defs1.txt").write_text("""
foo = [FOO]

@import defs2.txt
""")

# …that, in turn, uses it in a context
Path("defs2.txt").write_text("""
@context BAR
    [FOO] -> [mass]: value / foo * 10.0 kg
@end
""")


# Succeeds with both pint 0.18 and pint 0.19
ureg0 = pint.UnitRegistry()
ureg0.load_definitions("defs0.txt")

assert 12.0 == ureg0("1.2 foo").to("kg", "BAR").magnitude


# Succeeds with pint 0.18; fails with pint 0.19
ureg1 = pint.UnitRegistry()
ureg1.load_definitions("defs1.txt")  # ← FAILS

assert 12.0 == ureg1("1.2 foo").to("kg", "BAR").magnitude
```

The exception is:
```
Traceback (most recent call last):
  File "/home/khaeru/.local/lib/python3.9/site-packages/pint/context.py", line 323, in from_definition
    src = to_base_func(relation.src)
  File "/home/khaeru/.local/lib/python3.9/site-packages/pint/registry.py", line 770, in get_dimensionality
    return self._get_dimensionality(input_units)
  File "/home/khaeru/.local/lib/python3.9/site-packages/pint/registry.py", line 787, in _get_dimensionality
    self._get_dimensionality_recurse(input_units, 1, accumulator)
  File "/home/khaeru/.local/lib/python3.9/site-packages/pint/registry.py", line 802, in _get_dimensionality_recurse
    reg = self._dimensions[key]
KeyError: '[FOO]'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/khaeru/vc/iiasa/units/tmp/bug.py", line 39, in <module>
    ureg1.load_definitions("defs1.txt")
  File "/home/khaeru/.local/lib/python3.9/site-packages/pint/registry.py", line 650, in load_definitions
    loaderfunc(definition)
  File "/home/khaeru/.local/lib/python3.9/site-packages/pint/registry.py", line 1629, in _load_context
    self.add_context(Context.from_definition(cd, self.get_dimensionality))
  File "/home/khaeru/.local/lib/python3.9/site-packages/pint/context.py", line 331, in from_definition
    raise DefinitionSyntaxError(
  File "<string>", line 3
pint.errors.DefinitionSyntaxError: Could not add Context BAR relation on line '3'
```

**Comment by hgrecco** [comment]
Confirmed. Fixing ASAP

**Comment by hgrecco** [comment]
@khaeru Can you check if the current version in develop fixes your real example?

**Comment by khaeru** [comment]
Thanks for the quick response!

I ran:
```
$ pip install git+https://github.com/hgrecco/pint.git@develop
…
Successfully installed Pint-0.20.dev2+gc6c0050                                                                                                     
```

Then I tried to run the full code from which I had distilled the minimal example above to reproduce the bug. Specifically, I ran `pytest` on IAMconsortium/units, which essentially loads the definitions.txt and related files from https://github.com/IAMconsortium/units/tree/main/iam_units/data.

I now see this exception:
```
iam_units/__init__.py:18: in <module>
    registry.load_definitions(str(Path(__file__).parent / "data" / "definitions.txt"))
../../../.local/lib/python3.9/site-packages/pint/registry.py:640: in load_definitions
    for lineno, definition in parsed_files.iter_definitions():
../../../.local/lib/python3.9/site-packages/pint/parser.py:90: in iter_definitions
    yield from self._iter_definitions(*self)
../../../.local/lib/python3.9/site-packages/pint/parser.py:79: in _iter_definitions
    yield from self._iter_definitions(*pending_files)
../../../.local/lib/python3.9/site-packages/pint/parser.py:76: in _iter_definitions
    f"found {pending_files[0].path})"
E   AttributeError: 'DefinitionFile' object has no attribute 'path'
```

**Comment by khaeru** [comment]
If it helps, replacing `pending_files[0].path` with `pending_files[0].filename.name` in the installed code from the `develop` branch gives:
```
E   ValueError: The order of the files do not match. (expected: metrics.txt, found species.txt)
```

Thus some more details about:

> definitions.txt and related files from https://github.com/IAMconsortium/units/tree/main/iam_units/data.

These files use @import recursively. The structure is roughly this, in this specific order.

- definitions.txt
  - @import emissions.txt
    - @import species.txt
    - @import metrics.txt
      - @import A.txt
      - @import B.txt
      - @import C.txt
      - etc.

I haven't closely read the new method & related code on the branch, but perhaps it is not handling this kind of structure.

**Comment by jules-ch** [comment]
I get the use case, I don't know if in the future we will keep this feature.
We might deprecate this, I don't know if reading recursively was inteded in the first place(ping @hgrecco) it can lead to inifinite loop & weird stuff.

**Comment by khaeru** [comment]
> infinite loop & weird stuff.

Sure, I definitely wouldn't expect support for that kind of weird stuff. People writing definitions files in that way would only confuse themselves. We are only using a simple tree to organize a large number of lines into smaller files.

But this is a breaking change not mentioned in the CHANGES file (also: it would be nice to include that file in the built docs on RTD, where the other breaking changes could be seen more easily 🙏🏾 ). For deprecation, we'd expect it to continue to work in 0.19 while raising a warning, then fail in 0.20 or later.

**Comment by hgrecco** [comment]
Thanks again for taking the time to evaluate and report. This bug is due to no the new parser and loader. While recursive imports were not originally supported by design, they work, and they should continue working. I think I have pinpointed the problem and I will produce a fix today.

**Comment by hgrecco** [comment]
@khaeru Can you try the current develop? I added a test for nested files and some extra code to properly support it.

**Comment by khaeru** [comment]
```
Successfully installed Pint-0.20.dev3+gc338b35
```
…and our code/test suite works again! 🥳 

Thank you for the fix, much appreciated.

**Comment by hgrecco** [comment]
Fixed in 0.19.1 !

**Comment by danielhuppmann** [comment]
Thanks for the fix, @hgrecco - but it seems that some (related?) issue persists on Windows, see https://github.com/IAMconsortium/pyam/runs/5852337735

```
E   ValueError: The order of the files do not match. (expected: emissions/emissions.txt, found C:\hostedtoolcache\windows\Python\3.10.4\x64\Lib\site-packages\iam_units\data\emissions\emissions.txt)
```

The failing workflows already uses pint 19.1.

**Comment by danielhuppmann** [comment]
py3.7 is still using pint 0.18, because you dropped support for 3.7 with the latest release...

**Comment by hgrecco** [comment]
I think if you change in:
https://github.com/hgrecco/pint/blob/3b99ee6c02786a2aa31660e67ed8d2ebde23ebd2/pint/parser.py#L83

`pending_files[0].filename` to `pending_files[0].filename.as_posix()` should fix it
